[metadata]
name = galleries
version = attr: galleries.__version__
author = Dylan Maltby
description = Organize gallery tags in a CSV file

[options]
include_package_data = True
packages =
    galleries
    galleries.cli
python_requires = >=3.11
install_requires =
    rich

[options.extras_require]
TOML =

[options.entry_points]
console_scripts =
    galleries = galleries.cli:main
